#!/usr/bin/env python3
"""
Gentoo Installer — FSTAB Module
Generate /etc/fstab
"""

import subprocess
import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger("gentoo-installer")


# Filesystem mount options
FS_OPTIONS = {
    "ext4": "defaults,noatime",
    "ext2": "defaults,noatime",
    "btrfs": "defaults,noatime,compress=zstd",
    "xfs": "defaults,noatime",
    "fat32": "defaults",
    "swap": "sw",
}


def get_partition_uuid(partition_path: str) -> Optional[str]:
    """Get UUID of a partition using blkid"""
    try:
        result = subprocess.run(
            ["blkid", "-s", "UUID", "-o", "value", partition_path],
            capture_output=True, text=True, check=True
        )
        uuid = result.stdout.strip()
        return uuid if uuid else None
    except subprocess.CalledProcessError:
        return None


def generate_fstab_line(mount: str, partition_path: str, fs: str) -> str:
    """Generate a single fstab line"""
    if fs == "swap":
        return f"{partition_path} none swap defaults 0 0"

    uuid = get_partition_uuid(partition_path)
    device = f"UUID={uuid}" if uuid else partition_path

    options = FS_OPTIONS.get(fs, "defaults")

    # EFI partition options
    if mount == "/boot/efi":
        options = "defaults,noatime"

    # Dump and pass
    dump = 0
    pass_num = 0
    if mount == "/":
        pass_num = 1
    elif fs in ("ext4", "ext2", "btrfs", "xfs"):
        pass_num = 2

    return f"{device} {mount} {fs} {options} {dump} {pass_num}"


def generate_fstab(root: Path, disk: str, partitions: list[dict]) -> bool:
    """
    Generate /etc/fstab based on partition scheme
    root: install root (/mnt/gentoo)
    disk: disk name (e.g., nvme0n1)
    partitions: list of {"mount": "/", "fs": "ext4", ...}
    """
    root = Path(root)
    fstab_path = root / "etc/fstab"

    logger.info(f"Generating fstab at {fstab_path}")

    # Detect partition paths
    disk_path = f"/dev/{disk}"
    prefix = f"{disk_path}p" if "nvme" in disk or "mmc" in disk else disk_path

    lines = [
        "# /etc/fstab: static file system information.",
        "# <fs>         <mountpoint>  <type>  <opts>         <dump/pass>",
        "# Generated by Gentoo Installer",
        "",
    ]

    for i, part in enumerate(partitions):
        mount = part.get("mount", "")
        fs = part.get("fs", "ext4")
        part_num = i + 1
        partition_path = f"{prefix}{part_num}"

        if not Path(partition_path).exists():
            # Try alternate naming
            alt_path = f"{disk_path}{part_num}"
            if Path(alt_path).exists():
                partition_path = alt_path
            else:
                logger.warning(f"Partition {partition_path} not found, skipping")
                continue

        line = generate_fstab_line(mount, partition_path, fs)
        lines.append(line)
        logger.info(f"fstab: {line}")

    # Add tmpfs entries
    lines.append("")
    lines.append("# tmpfs")
    lines.append("tmpfs   /tmp    tmpfs   defaults,noatime,mode=1777   0   0")
    lines.append("tmpfs   /run    tmpfs   defaults,noatime,mode=0755   0   0")
    lines.append("")
    lines.append("# proc and sysfs")
    lines.append("proc    /proc   proc    defaults    0   0")
    lines.append("sysfs   /sys    sysfs   defaults    0   0")
    lines.append("devpts  /dev/pts  devpts  defaults,gid=5,mode=620  0  0")
    lines.append("")

    try:
        with open(fstab_path, "w") as f:
            f.write("\n".join(lines) + "\n")
        logger.info(f"Written fstab to {fstab_path}")
        return True

    except IOError as e:
        logger.error(f"Error writing fstab: {e}")
        return False
