#!/usr/bin/env python3
"""
Gentoo Installer — Portage Module
make.conf, make.profile, emerge, repositories
"""

import subprocess
import logging
import os
from pathlib import Path
from typing import Optional

logger = logging.getLogger("gentoo-installer")


def configure_make_conf(root: Path, config: dict) -> bool:
    """
    Write /etc/portage/make.conf
    CFLAGS, CXXFLAGS, MAKEOPTS, USE, VIDEO_CARDS, GRUB_PLATFORMS
    """
    root = Path(root)
    make_conf = root / "etc/portage/make.conf"
    make_conf.parent.mkdir(parents=True, exist_ok=True)

    nproc = os.cpu_count() or 4
    cflags = "-march=native -O2 -pipe"
    cxxflags = cflags

    use_flags = config.get("use_flags_global", "")
    use_flags_list = [
        "systemd",
        "wayland",
        "pipewire",
        "pulseaudio",
        "bluetooth",
        "elogind",
        "udev",
        "dbus",
        "policykit",
        "X",
        "vulkan",
        "drm",
        "gbm",
    ]

    # Remove systemd if using OpenRC
    if config.get("init_system", "openrc") == "openrc":
        use_flags_list = [f for f in use_flags_list if f != "systemd"]
        use_flags_list.append("-systemd")

    # Add per-package USE flags
    use_flags_str = " ".join(use_flags_list)
    if use_flags:
        use_flags_str += f" {use_flags}"

    video_cards = config.get("video_cards", "")
    grub_platforms = config.get("grub_platforms", "efi-64")

    content = f"""# Generated by Gentoo Installer
# https://wiki.gentoo.org/wiki/Handbook:AMD64/Working/USE

CFLAGS="{cflags}"
CXXFLAGS="${{CFLAGS}}"

# Parallel jobs
MAKEOPTS="-j{nproc}"

# CPU features
CPU_FLAGS_X86="mmx mmxext sse sse2 sse3 ssse3 sse4_1 sse4_2 avx avx2 fma3"

# USE flags
USE="{use_flags_str}"

# Video cards
VIDEO_CARDS="{video_cards}"

# Bootloader
GRUB_PLATFORMS="{grub_platforms}"

# Accept license
ACCEPT_LICENSE="* -@EULA"

# Portage features
FEATURES="parallel-install parallel-fetch"

# emerge default options
EMERGE_DEFAULT_OPTS="--jobs={nproc} --load-average={nproc}"
"""

    try:
        with open(make_conf, "w") as f:
            f.write(content)
        logger.info(f"Written {make_conf}")
        return True

    except IOError as e:
        logger.error(f"Error writing make.conf: {e}")
        return False


def write_package_use(root: Path, use_flags: dict[str, str]) -> bool:
    """Write per-package USE flags to /etc/portage/package.use/custom"""
    root = Path(root)
    pkg_use = root / "etc/portage/package.use/custom"
    pkg_use.parent.mkdir(parents=True, exist_ok=True)

    try:
        with open(pkg_use, "w") as f:
            f.write("# Generated by Gentoo Installer\n\n")
            for pkg, flags in use_flags.items():
                f.write(f"{pkg} {flags}\n")
        logger.info(f"Written {pkg_use}")
        return True

    except IOError as e:
        logger.error(f"Error writing package.use: {e}")
        return False


def write_package_keywords(root: Path, keywords: list[str]) -> bool:
    """Write ~amd64 keywords to package.accept_keywords"""
    root = Path(root)
    pkg_kw = root / "etc/portage/package.accept_keywords/custom"
    pkg_kw.parent.mkdir(parents=True, exist_ok=True)

    try:
        with open(pkg_kw, "w") as f:
            f.write("# Generated by Gentoo Installer\n\n")
            for pkg in keywords:
                f.write(f"{pkg} ~amd64\n")
        logger.info(f"Written {pkg_kw}")
        return True

    except IOError as e:
        logger.error(f"Error writing package.accept_keywords: {e}")
        return False


def write_package_mask(root: Path, masked: list[str]) -> bool:
    """Write package masks"""
    root = Path(root)
    pkg_mask = root / "etc/portage/package.mask/custom"
    pkg_mask.parent.mkdir(parents=True, exist_ok=True)

    try:
        with open(pkg_mask, "w") as f:
            f.write("# Generated by Gentoo Installer\n\n")
            for pkg in masked:
                f.write(f"{pkg}\n")
        return True

    except IOError as e:
        logger.error(f"Error writing package.mask: {e}")
        return False


def set_profile(root: Path, profile: str) -> bool:
    """Set Gentoo profile using eselect"""
    from . import chroot

    logger.info(f"Setting profile: {profile}")
    result = chroot.eselect_in_chroot(root, "profile", f"set {profile}")

    if result.ok:
        logger.info(f"Profile set to {profile}")
        return True
    else:
        logger.error(f"Failed to set profile: {result.stderr}")
        return False


def list_profiles(root: Path) -> list[str]:
    """List available Gentoo profiles"""
    from . import chroot

    result = chroot.eselect_in_chroot(root, "profile", "list")
    if result.ok:
        return result.stdout.strip().splitlines()
    return []


def sync_portage(root: Path) -> bool:
    """Sync portage tree"""
    from . import chroot

    logger.info("Syncing portage tree")
    result = chroot.chroot_run(root, "emerge --sync")

    if result.ok:
        logger.info("Portage tree synced")
        return True
    else:
        logger.error(f"Failed to sync portage: {result.stderr}")
        return False


def emerge(root: Path, packages: list[str], flags: str = "", verbose: bool = True) -> bool:
    """
    Emerge packages
    packages: list of package atoms
    flags: additional emerge flags
    """
    from . import chroot

    if not packages:
        logger.info("No packages to emerge")
        return True

    logger.info(f"Emerging: {' '.join(packages)}")

    # Build emerge command
    cmd_parts = ["emerge", "--ask=n"]
    if verbose:
        cmd_parts.append("--verbose")
    if flags:
        cmd_parts.append(flags)
    cmd_parts.extend(packages)

    cmd = " ".join(cmd_parts)
    result = chroot.chroot_run(root, cmd, timeout=None)

    if result.ok:
        logger.info(f"Successfully emerged: {' '.join(packages)}")
        return True
    else:
        logger.error(f"Failed to emerge packages: {result.stderr[-500:]}")
        return False


def setup_repositories(root: Path, overlays: list[str]) -> bool:
    """
    Setup overlays using eselect-repository
    overlays: list of overlay names (guru, hyproverlay, etc.)
    """
    from . import chroot

    for overlay in overlays:
        logger.info(f"Setting up overlay: {overlay}")

        # Check if already exists
        check = chroot.chroot_run(root, f"eselect repository list 2>/dev/null | grep {overlay}")
        if check.ok and overlay in check.stdout:
            logger.info(f"Overlay {overlay} already exists")
            # Sync it
            chroot.chroot_run(root, f"emaint sync -r {overlay}")
            continue

        # Add overlay
        if overlay == "guru":
            cmd = f"eselect repository add guru git https://github.com/gentoo-mirror/guru"
        elif overlay == "hyproverlay":
            cmd = f"eselect repository add hyproverlay git https://codeberg.org/hyprland-overlay/hyprland-overlay.git"
        else:
            cmd = f"eselect repository add {overlay}"

        result = chroot.chroot_run(root, cmd)
        if not result.ok:
            logger.warning(f"Failed to add overlay {overlay}: {result.stderr}")
            continue

        # Sync
        chroot.chroot_run(root, f"emaint sync -r {overlay}")
        logger.info(f"Overlay {overlay} added and synced")

    return True


def accept_keywords(root: Path, packages: list[str]) -> bool:
    """Accept ~amd64 keywords for packages"""
    root = Path(root)
    ak_file = root / "etc/portage/package.accept_keywords/custom"
    ak_file.parent.mkdir(parents=True, exist_ok=True)

    try:
        with open(ak_file, "a") as f:
            f.write("\n# Additional keywords\n")
            for pkg in packages:
                f.write(f"{pkg} ~amd64\n")
        return True
    except IOError as e:
        logger.error(f"Error writing keywords: {e}")
        return False


def setup_base_system(root: Path) -> bool:
    """Install base system packages"""
    base_packages = [
        "sys-kernel/linux-firmware",
        "sys-firmware/intel-microcode",
        "sys-firmware/amd-ucode",
        "net-misc/dhcpcd",
        "net-misc/openssh",
        "sys-process/htop",
        "app-editors/vim",
        "app-shells/zsh",
        "sys-auth/sudo",
        "sys-apps/mlocate",
        "sys-apps/pciutils",
        "sys-apps/usbutils",
    ]

    return emerge(root, base_packages)
